language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nighly
        - php: 7.0

before_script:
  - composer self-update
  - composer install --prefer-dist

services:
  - redis-server