sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nighly
        - php: 7.0
    fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

services:
  - redis-server

cache:
  directories:
    - vendor
    - $HOME/.composer/cache